import { Job } from '@/types';
import { Property } from '@/lib/firestore';

// Mock Properties Data
export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    name: 'Wohnkomplex Seeblick',
    address: 'Seestraße 123, 10115 Berlin',
    type: 'Wohnkomplex',
    status: 'active',
    owner: 'Immobilien GmbH',
    monthlyIncome: 25000,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-05-20'),
  },
  {
    id: 'prop-2',
    name: 'Bürogebäude Zentrum',
    address: 'Hauptplatz 42, 80331 München',
    type: 'Bürogebäude',
    status: 'active',
    owner: 'Business Properties AG',
    monthlyIncome: 45000,
    createdAt: new Date('2023-02-08'),
    updatedAt: new Date('2023-06-14'),
  },
  {
    id: 'prop-3',
    name: 'Appartementkomplex Stadtpark',
    address: 'Parkstraße 78, 20095 Hamburg',
    type: 'Wohnkomplex',
    status: 'active',
    owner: 'Norddeutsche Wohnbau KG',
    monthlyIncome: 38000,
    createdAt: new Date('2023-03-22'),
    updatedAt: new Date('2023-07-01'),
  },
  {
    id: 'prop-4',
    name: 'Einkaufszentrum Ost',
    address: 'Ostweg 100, 01067 Dresden',
    type: 'Einkaufszentrum',
    status: 'active',
    owner: 'Retail Invest Dresden GmbH',
    monthlyIncome: 75000,
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2023-08-12'),
  },
  {
    id: 'prop-5',
    name: 'Lagerhalle West',
    address: 'Industriestr. 200, 50667 Köln',
    type: 'Industriegebäude',
    status: 'active',
    owner: 'Logistik & Lager GmbH',
    monthlyIncome: 15000,
    createdAt: new Date('2023-05-17'),
    updatedAt: new Date('2023-09-03'),
  }
];

// Mock Jobs Data
export const mockJobs: Job[] = [
  {
    id: 'job-1',
    propertyId: 'prop-1',
    title: 'Heizungsreparatur in Wohnung 12',
    description: 'Die Heizung in Wohnung 12 funktioniert nicht richtig. Der Mieter berichtet, dass sie nicht über 18 Grad erhitzt.',
    status: 'open',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-15'),
    createdBy: 'max.mustermann@example.com',
    priority: 'high',
    jobType: 'sonderauftrag',
  },
  {
    id: 'job-2',
    propertyId: 'prop-2',
    title: 'Jährliche Inspektion der Brandmelder',
    description: 'Routinemäßige Inspektion aller Brandmelder im Gebäude durchführen.',
    status: 'in-progress',
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2023-06-17'),
    createdBy: 'thomas.weber@example.com',
    assignedTo: 'thomas.weber@example.com',
    dueDate: new Date('2023-07-10'),
    jobType: 'liegenschaftsauftrag',
  },
  {
    id: 'job-3',
    propertyId: 'prop-1',
    title: 'Graffiti an der Außenwand entfernen',
    description: 'Graffiti an der Nordseite des Gebäudes entfernen und die Wand neu streichen.',
    status: 'closed',
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date('2023-06-05'),
    createdBy: 'anna.schmidt@example.com',
    completedAt: new Date('2023-06-05'),
    jobType: 'liegenschaftsauftrag',
  },
  {
    id: 'job-4',
    propertyId: 'prop-3',
    title: 'Wasserrohrbruch in der Tiefgarage',
    description: 'Wasserrohrbruch in der Tiefgarage neben Stellplatz 15. Der Bereich ist bereits abgesperrt.',
    status: 'open',
    createdAt: new Date('2023-06-18'),
    updatedAt: new Date('2023-06-18'),
    createdBy: 'max.mustermann@example.com',
    priority: 'high',
    jobType: 'wasserschaden',
  },
  {
    id: 'job-5',
    propertyId: 'prop-4',
    title: 'Neuer Schließanlage installieren',
    description: 'Installation einer neuen Schließanlage für das gesamte Gebäude nach mehreren verlorenen Schlüsseln.',
    status: 'canceled',
    createdAt: new Date('2023-05-05'),
    updatedAt: new Date('2023-05-12'),
    createdBy: 'julia.becker@example.com',
    notes: 'Storniert aufgrund von Budgetkürzungen.',
    jobType: 'sonderauftrag',
  },
  {
    id: 'job-6',
    propertyId: 'prop-1',
    title: 'Erneuerung der Gartenbepflanzung',
    description: 'Die Grünanlagen rund um den Wohnkomplex sollen neu bepflanzt werden.',
    status: 'new',
    priority: 'low',
    createdAt: new Date('2023-10-09'),
    dueDate: new Date('2023-11-30'),
    notes: 'Planung für das Frühjahr 2024.',
    jobType: 'liegenschaftsauftrag',
  },
  {
    id: 'job-7',
    propertyId: 'prop-2',
    title: 'Modernisierung der Aufzüge',
    description: 'Die Aufzugsanlage im Bürogebäude soll modernisiert werden, um Energieeffizienz zu verbessern.',
    status: 'canceled',
    priority: 'medium',
    createdAt: new Date('2023-08-15'),
    dueDate: new Date('2023-12-01'),
    assignedTo: 'Lift & Aufzug GmbH',
    notes: 'Projekt wurde aus Budgetgründen auf nächstes Jahr verschoben.',
    jobType: 'baustelle',
  }
];

// Mock employees data
export const mockEmployees = [
  {
    id: 'employee-1',
    firstName: 'Max',
    lastName: 'Mustermann',
    email: 'max.mustermann@example.com',
    phone: '+49 123 4567890',
    position: 'Hausmeister',
    role: 'admin',
    assignedProperties: ['property-1', 'property-2'],
    isActive: true,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-06-20')
  },
  {
    id: 'employee-2',
    firstName: 'Anna',
    lastName: 'Schmidt',
    email: 'anna.schmidt@example.com',
    phone: '+49 234 5678901',
    position: 'Reinigungskraft',
    role: 'mitarbeiter',
    assignedProperties: ['property-3'],
    isActive: true,
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2023-05-15')
  },
  {
    id: 'employee-3',
    firstName: 'Thomas',
    lastName: 'Weber',
    email: 'thomas.weber@example.com',
    phone: '+49 345 6789012',
    position: 'Techniker',
    role: 'mitarbeiter',
    assignedProperties: ['property-1', 'property-4'],
    isActive: true,
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2023-07-01')
  },
  {
    id: 'employee-4',
    firstName: 'Julia',
    lastName: 'Becker',
    email: 'julia.becker@example.com',
    phone: '+49 456 7890123',
    position: 'Bürokraft',
    role: 'mitarbeiter',
    assignedProperties: [],
    isActive: false,
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date('2023-04-30')
  }
];
