
import { Property, Job } from '@/types';

// Mock Properties Data
export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    name: 'Wohnkomplex Seeblick',
    address: 'Seestraße 123',
    city: 'Berlin',
    postalCode: '10115',
    type: 'Wohnkomplex',
    size: 2500,
    owner: 'Immobilien GmbH',
    contactPhone: '+49 30 12345678',
    contactEmail: 'kontakt@immobilien-gmbh.de',
    notes: 'Wohnkomplex mit 25 Wohneinheiten, Baujahr 2010.',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-05-20'),
  },
  {
    id: 'prop-2',
    name: 'Bürogebäude Zentrum',
    address: 'Hauptplatz 42',
    city: 'München',
    postalCode: '80331',
    type: 'Bürogebäude',
    size: 1800,
    owner: 'Business Properties AG',
    contactPhone: '+49 89 98765432',
    contactEmail: 'info@business-properties.de',
    notes: 'Modernes Bürogebäude mit 6 Etagen und Tiefgarage.',
    createdAt: new Date('2023-02-08'),
    updatedAt: new Date('2023-06-14'),
  },
  {
    id: 'prop-3',
    name: 'Appartementkomplex Stadtpark',
    address: 'Parkstraße 78',
    city: 'Hamburg',
    postalCode: '20095',
    type: 'Wohnkomplex',
    size: 3200,
    owner: 'Norddeutsche Wohnbau KG',
    contactPhone: '+49 40 44556677',
    contactEmail: 'kontakt@nordwohnbau.de',
    notes: 'Komplex mit 42 Appartements, Baujahr 2015, mit Gemeinschaftsgarten.',
    createdAt: new Date('2023-03-22'),
    updatedAt: new Date('2023-07-01'),
  },
  {
    id: 'prop-4',
    name: 'Einkaufszentrum Ost',
    address: 'Ostweg 100',
    city: 'Dresden',
    postalCode: '01067',
    type: 'Einkaufszentrum',
    size: 5000,
    owner: 'Retail Invest Dresden GmbH',
    contactPhone: '+49 351 11223344',
    contactEmail: 'info@retail-dresden.de',
    notes: 'Einkaufszentrum mit 35 Geschäften, Foodcourt und Kino.',
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2023-08-12'),
  },
  {
    id: 'prop-5',
    name: 'Lagerhalle West',
    address: 'Industriestr. 200',
    city: 'Köln',
    postalCode: '50667',
    type: 'Industriegebäude',
    size: 4200,
    owner: 'Logistik & Lager GmbH',
    contactPhone: '+49 221 55667788',
    contactEmail: 'kontakt@logistik-lager.de',
    notes: 'Moderne Lagerhalle mit automatisierten Systemen, Baujahr 2018.',
    createdAt: new Date('2023-05-17'),
    updatedAt: new Date('2023-09-03'),
  }
];

// Mock Jobs Data
export const mockJobs: Job[] = [
  {
    id: 'job-1',
    propertyId: 'prop-1',
    title: 'Reparatur defekter Heizungen',
    description: 'In mehreren Wohnungen sind Heizungsprobleme gemeldet worden. Inspektion und Reparatur erforderlich.',
    status: 'inprogress',
    priority: 'high',
    createdAt: new Date('2023-10-05'),
    dueDate: new Date('2023-10-15'),
    completedAt: null,
    assignedTo: 'Heizungstechniker Schmidt',
    notes: 'Ersatzteile wurden bestellt, Lieferung für 10.10. erwartet.',
  },
  {
    id: 'job-2',
    propertyId: 'prop-2',
    title: 'Reinigung der Fensterfassade',
    description: 'Regelmäßige Reinigung der Glasfassade des Bürogebäudes.',
    status: 'completed',
    priority: 'medium',
    createdAt: new Date('2023-09-20'),
    dueDate: new Date('2023-10-01'),
    completedAt: new Date('2023-09-30'),
    assignedTo: 'Gebäudereinigung ProClean',
    notes: 'Arbeiten wurden zur vollsten Zufriedenheit ausgeführt.',
  },
  {
    id: 'job-3',
    propertyId: 'prop-3',
    title: 'Erneuerung der Eingangstüren',
    description: 'Die Eingangstüren müssen gegen neue, sicherere Modelle ausgetauscht werden.',
    status: 'new',
    priority: 'medium',
    createdAt: new Date('2023-10-08'),
    dueDate: new Date('2023-11-15'),
    completedAt: null,
    assignedTo: null,
    notes: 'Angebote von 3 Firmen einholen.',
  },
  {
    id: 'job-4',
    propertyId: 'prop-4',
    title: 'Wartung der Klimaanlage',
    description: 'Jährliche Wartung der zentralen Klimaanlage des Einkaufszentrums.',
    status: 'onhold',
    priority: 'low',
    createdAt: new Date('2023-09-15'),
    dueDate: new Date('2023-10-20'),
    completedAt: null,
    assignedTo: 'Klima-Technik Service GmbH',
    notes: 'Wartung verschoben wegen fehlender Ersatzteile. Neuer Termin wird vereinbart.',
  },
  {
    id: 'job-5',
    propertyId: 'prop-5',
    title: 'Installation neuer Sicherheitskameras',
    description: 'Installation eines erweiterten Kamerasystems für bessere Überwachung der Lagerhalle.',
    status: 'inprogress',
    priority: 'high',
    createdAt: new Date('2023-10-01'),
    dueDate: new Date('2023-10-25'),
    completedAt: null,
    assignedTo: 'SecTech Solutions',
    notes: 'Erste Phase der Installation abgeschlossen. Verkabelung fertig, Kamerainstallation beginnt nächste Woche.',
  },
  {
    id: 'job-6',
    propertyId: 'prop-1',
    title: 'Erneuerung der Gartenbepflanzung',
    description: 'Die Grünanlagen rund um den Wohnkomplex sollen neu bepflanzt werden.',
    status: 'new',
    priority: 'low',
    createdAt: new Date('2023-10-09'),
    dueDate: new Date('2023-11-30'),
    completedAt: null,
    assignedTo: null,
    notes: 'Planung für das Frühjahr 2024.',
  },
  {
    id: 'job-7',
    propertyId: 'prop-2',
    title: 'Modernisierung der Aufzüge',
    description: 'Die Aufzugsanlage im Bürogebäude soll modernisiert werden, um Energieeffizienz zu verbessern.',
    status: 'canceled',
    priority: 'medium',
    createdAt: new Date('2023-08-15'),
    dueDate: new Date('2023-12-01'),
    completedAt: null,
    assignedTo: 'Lift & Aufzug GmbH',
    notes: 'Projekt wurde aus Budgetgründen auf nächstes Jahr verschoben.',
  }
];
